USE [master]
GO

/****** Object:  Database [Order2Db]    Script Date: 21/11/2018 10:33:17 ******/
CREATE DATABASE [Order2Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Order2Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Order2Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Order2Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Order2Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Order2Db] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Order2Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Order2Db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Order2Db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Order2Db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Order2Db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Order2Db] SET ARITHABORT OFF 
GO

ALTER DATABASE [Order2Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Order2Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Order2Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Order2Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Order2Db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Order2Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Order2Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Order2Db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Order2Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Order2Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Order2Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Order2Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Order2Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Order2Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Order2Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Order2Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Order2Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Order2Db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Order2Db] SET  MULTI_USER 
GO

ALTER DATABASE [Order2Db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Order2Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Order2Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Order2Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Order2Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Order2Db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Order2Db] SET  READ_WRITE 
GO


